### ISSUE TITLE
Current head won't build

### ISSUE THREAD

**Issue by ericbarnhill** [imagej/imagej-matlab#11]
Hi, I'd like to work on a clone of this code to try to resolve some issues. It fails to run for one reason or another on R2014a (on Windows in my desktop) and R2015a and R2016b (on my laptop) and also Gnu Octave 4.3. The reasons are different for each. I am happy to contribute. Unfortunately the current head does not build. I get the error:

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-rules) @ imagej-matlab ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.131 s
[INFO] Finished at: 2017-02-22T15:44:01+01:00
[INFO] Final Memory: 22M/602M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project imagej-matlab: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed: For artifact {null:null:null:jar}: The groupId cannot be empty. -> [Help 1]

I even purged the gov branch of my maven repo to ensure it wasn't (I don't think) on my end. Is anyone else getting this error. If so, could anyone please tell me the last commit of the code that builds successfully, and I will start from there. Thank you.

**Comment by imagejan** [comment]
Builds fine for me, when running `mvn` from the command line on current master.
How did you run the build?

**Comment by ericbarnhill** [comment]
mvn compile

**Comment by ericbarnhill** [comment]
I will get rid of my whole maven repo and try again

**Comment by imagejan** [comment]
Strange. I get a warning, but otherwise it builds fine:

```text
mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ImageJ-MATLAB 0.7.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-rules) @ imagej-matlab -
--
[WARNING] Could not find junit:junit:jar:4.12:test at null
[INFO]
[INFO] --- build-helper-maven-plugin:1.12:regex-property (sanitize-version) @ im
agej-matlab ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ imagej-matlab ---
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: E:\git\imagej-matlab
[INFO] Storing buildNumber: 9a04921e5667b61f1d839bf6f63bb04c8fc71a44 at timestam
p: 1487775697528
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] --- scijava-maven-plugin:1.0.0:set-rootdir (set-rootdir) @ imagej-matlab
---
[INFO] Setting rootdir: E:\git\imagej-matlab
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ imagej-m
atlab ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ imagej-matlab
 ---
[INFO] Compiling 8 source files to E:\git\imagej-matlab\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.022 s
[INFO] Finished at: 2017-02-22T16:01:38+01:00
[INFO] Final Memory: 67M/2637M
[INFO] ------------------------------------------------------------------------
```

**Comment by ericbarnhill** [comment]
Getting rid of my entire maven repo and starting over has resolved the issue. Must have had a corruption in there. Sorry to disturb you and looking forward to contributing a few edits, if accepted.
