### ISSUE TITLE
ImageJ.m without opening imagej does not work

### ISSUE THREAD

**Issue by mkitti** [imagej/imagej-matlab#24]
```
>> ImageJ(false);
No method 'start' with matching signature found for class 'net.imagej.matlab.ImageJMATLAB'.

Error in ImageJ (line 45)
        ImageJMATLAB.start('--headless');
```

I believe the line should be
```
ImageJMATLAB.start(verbose,'--headless');
```

**Comment by mkitti** [comment]
My ImageJ.m was out of date somehow

**Comment by imagejan** [comment]
It seems that the `ImageJ.m` script served by the update site (https://sites.imagej.net/MATLAB/scripts/ImageJ.m-20151012112000) is actually not up to date with this repository: https://github.com/imagej/imagej-matlab/blob/570036f79904b99201a7c05cc69b81f916a60d5b/src/scripts/update/ImageJ.m

@ctrueden @hinerm could you maybe upload the latest version?

**Comment by hinerm** [comment]
@imagejan [done](https://sites.imagej.net/MATLAB/scripts/ImageJ.m-20211122095725).. thanks for noticing!
