### ISSUE TITLE
ImageJ_Test.m calls Miji()

### ISSUE THREAD

**Issue by bastelflp** [imagej/imagej-matlab#4]
[ImageJ_Test.m](https://github.com/imagej/imagej-matlab/blob/master/src/scripts/update/ImageJ_Test.m#L1) calls `Miji()` instead of `ImageJ()` - is that done on purpose?

**Comment by ctrueden** [comment]
@bastelflp I'm guessing it is an oversight, left over from the Miji days, although @hinerm would know for sure.

**Comment by hinerm** [comment]
@bastelflp @ctrueden agreed that it's an oversight
