### ISSUE TITLE
Cannot run ImageJ.m from MATLAB.

### ISSUE THREAD

**Issue by tinevez** [imagej/imagej-matlab#7]
One cannot run `ImageJ.m` from MATLAB, after following the installation instructions. The following command

``` matlab
>> ImageJ
```

yields

``` matlab
Undefined function 'start' for input arguments of type 'net.imagej.matlab.ImageJMATLAB'.

Error in ImageJ (line 42)
        ImageJMATLAB.start();
 ```

Tested with MATLAB R2016a and R2016b, on Windows 10 and on MacOSX El Capitan.

**Comment by tinevez** [comment]
Investigating:

- the jars are on MATLAB classpath:
``` matlab
>> javaclasspath
...
/Users/tinevez/Applications/Fiji.app/jars/imagej-matlab-0.7.1.jar 
...
/Users/tinevez/Applications/Fiji.app/jars/scripting-matlab-0.5.1.jar  
...
```

**Comment by tinevez** [comment]
See also this topic on the forum:
http://forum.imagej.net/t/why-im-using-miji-instead-of-imagej-matlab/3430

**Comment by tinevez** [comment]
Ok I think I have found the reason why.

Recent versions of MATLAB ship and use Java 1.7 by default. If you try to run anything Fiji from MATLAB with the 1.7 JVM, it will fail with the aforementioned, non easily relatable, error messages.

This also affects `Miji`, with other symptoms: Miji launches, but some Fiji classes cannot be accessed. For instance:
``` m
>> version -java

ans =
Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

>> Miji
Use MIJ.exit to end the session

--------------------------------------------------------------
MIJ 1.3.6-fiji: Matlab to ImageJ Interface
--------------------------------------------------------------
More Info: http://bigwww.epfl.ch/sage/soft/mij/
Help: MIJ.help
JVM> 1.3.6-fiji
JVM> Version: 1.7.0_75
JVM> Total amount of memory: 488448 Kb
JVM> Amount of free memory: 409978 Kb
ImageJ> Version:1.51h
ImageJ> Memory:93MB of 7458MB (1%)
ImageJ> Directory plugins: /Users/tinevez/Development/Fiji.app/plugins/
ImageJ> Directory macros: /Users/tinevez/Development/Fiji.app/macros/
ImageJ> Directory luts: /Users/tinevez/Development/Fiji.app/luts/
ImageJ> Directory image: Not specified
ImageJ> Directory imagej: /Users/tinevez/Development/Fiji.app/
ImageJ> Directory startup: /Users/tinevez/Development/Fiji.app/
ImageJ> Directory home: /Users/tinevez/
--------------------------------------------------------------
Status> ImageJ is running.
--------------------------------------------------------------

ans =
MIJ@138f483

>> model = fiji.plugin.trackmate.Model
Undefined variable "fiji" or class "fiji.plugin.trackmate.Model".
 ```

The solution is to launch MATLAB with the `MATLAB_JAVA` pointing to a 1.8 Java version. This is explained [here](https://fr.mathworks.com/matlabcentral/answers/103056-how-do-i-change-the-java-virtual-machine-jvm-that-matlab-is-using-for-mac-os).

NOTE: I tried with a recent jdk version:
`export MATLAB_JAVA=/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home`

and for reasons I do not understand MATLAB does not launch with a strange error message:
```
tinevez@lilium:/Applications/MATLAB_R2016b.app/bin$ ./matlab
Warning: Unable to find Java library: /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/lib/server/libjvm.dylib
Please check if you have a MATLAB_JAVA environment variable.
Note that MATLAB requires Java version 1.4 or higher.
Warning: Disabling Java support

                                                              < M A T L A B (R) >
                                                    Copyright 1984-2016 The MathWorks, Inc.
                                                     R2016b (9.1.0.441655) 64-bit (maci64)
                                                               September 7, 2016

Disabling Java support
 
For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.
 
>> 
```

However using a recent JRE works:
```
tinevez@lilium:/Applications/MATLAB_R2016b.app/bin$ export MATLAB_JAVA="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/"
tinevez@lilium:/Applications/MATLAB_R2016b.app/bin$ ./matlab
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
```

**Comment by ctrueden** [comment]
Great to hear that a Java 8 JRE works. I have heard that using Java 8 with MATLAB is pretty problematic, although I do not know specifics.

FWIW, I just downloaded and installed the latest R2017a prerelease of MATLAB on my macOS machine, and it still ships with Java 1.7.0_75. Too bad, so sad.

**Comment by ctrueden** [comment]
I [edited the ImageJ-MATLAB page](https://imagej.net/index.php?title=MATLAB_Scripting&type=revision&diff=25708&oldid=24946) to explain clearly that MATLAB must be switched to use Java 8, instead of the default Java 7.

**Comment by tinevez** [comment]
Thanks Curtis!
